name: Generate ASCII Artwork

on:
    push:
        branches:
            - main

jobs:
    ascii-art:
        runs-on: ubuntu-latest

        steps:
            # step 1: Checout repository
            - name: Checkout repository
              uses: actions/checkout@v4
            # step 2: To Install figlet tool via shell script method
            - name: Execute  Shell Script file
              run: ./ascii-script.sh