name: Sequential Jobs Example

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Build
        run: echo "Building the application..."

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 2 - Test
        run: echo "Running tests..."

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Step 3 - Deploy
        run: echo "Deploying application..."