name: Build-Test-Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application
        run: echo "Building app..."

  test:
    runs-on: ubuntu-latest
    needs: build           # Runs after 'build' job completes
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test           # Runs after 'test' job completes
    steps:
      - name: Deploy Application
        run: echo "Deploying app..."