name: Save Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          mkdir output
          echo "Build completed successfully" > output/build-log.txt

      - name: Upload Build Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: output/