name: Save Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          mkdir output
          echo "Build completed partially" > output/build-log.txt

      - name: Upload Build Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: output/         
          
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: downloaded_build

      - name: Display Build Log
        run: cat downloaded_build/build-log.txt